const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "923184474176";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923184474176,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Suhail-MD",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "It'x Suhail",

  sessionName:process.env.SESSION_ID || "SUHAIL_03_17_10_22_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTIwLFxuICAgICAgICAxNzAsXG4gICAgICAgIDE4MixcbiAgICAgICAgMTAsXG4gICAgICAgIDI0MixcbiAgICAgICAgMTIsXG4gICAgICAgIDEyLFxuICAgICAgICAxODcsXG4gICAgICAgIDg1LFxuICAgICAgICAxMTgsXG4gICAgICAgIDkwLFxuICAgICAgICA1OSxcbiAgICAgICAgMjM3LFxuICAgICAgICAxOTAsXG4gICAgICAgIDI3LFxuICAgICAgICA0MCxcbiAgICAgICAgNTEsXG4gICAgICAgIDEzOSxcbiAgICAgICAgMjA1LFxuICAgICAgICAxMTMsXG4gICAgICAgIDIyNyxcbiAgICAgICAgMjQ2LFxuICAgICAgICAyMCxcbiAgICAgICAgMTUsXG4gICAgICAgIDEyNyxcbiAgICAgICAgMjA5LFxuICAgICAgICAyNDUsXG4gICAgICAgIDIzMCxcbiAgICAgICAgMTE3LFxuICAgICAgICA3OCxcbiAgICAgICAgMzcsXG4gICAgICAgIDExOVxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxMTUsXG4gICAgICAgIDUyLFxuICAgICAgICAxNCxcbiAgICAgICAgNDcsXG4gICAgICAgIDI0NCxcbiAgICAgICAgOTcsXG4gICAgICAgIDEwNyxcbiAgICAgICAgMTcsXG4gICAgICAgIDMyLFxuICAgICAgICAxMzAsXG4gICAgICAgIDExMSxcbiAgICAgICAgMTIwLFxuICAgICAgICAyMTUsXG4gICAgICAgIDE3OCxcbiAgICAgICAgMSxcbiAgICAgICAgMjM3LFxuICAgICAgICAxODksXG4gICAgICAgIDIxNyxcbiAgICAgICAgMTM0LFxuICAgICAgICA5MSxcbiAgICAgICAgNzEsXG4gICAgICAgIDEwMCxcbiAgICAgICAgMTA0LFxuICAgICAgICAxODQsXG4gICAgICAgIDE1MCxcbiAgICAgICAgMjMsXG4gICAgICAgIDQzLFxuICAgICAgICAxNDksXG4gICAgICAgIDc4LFxuICAgICAgICA2OCxcbiAgICAgICAgOCxcbiAgICAgICAgMTE0XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyXCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxMjgsXG4gICAgICAgIDI0NCxcbiAgICAgICAgMjAsXG4gICAgICAgIDI0OCxcbiAgICAgICAgMTU3LFxuICAgICAgICAxMjAsXG4gICAgICAgIDExNyxcbiAgICAgICAgMTAzLFxuICAgICAgICA2MixcbiAgICAgICAgMTksXG4gICAgICAgIDE4MSxcbiAgICAgICAgMTg3LFxuICAgICAgICAzMSxcbiAgICAgICAgNDIsXG4gICAgICAgIDI1MCxcbiAgICAgICAgMTgwLFxuICAgICAgICAyNTAsXG4gICAgICAgIDcwLFxuICAgICAgICAzMCxcbiAgICAgICAgNDAsXG4gICAgICAgIDE3MCxcbiAgICAgICAgNDksXG4gICAgICAgIDIyNSxcbiAgICAgICAgMTE2LFxuICAgICAgICAyMDYsXG4gICAgICAgIDk1LFxuICAgICAgICAxODgsXG4gICAgICAgIDI0MCxcbiAgICAgICAgMjQsXG4gICAgICAgIDc2LFxuICAgICAgICAxODksXG4gICAgICAgIDc3XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDIyNSxcbiAgICAgICAgNTEsXG4gICAgICAgIDE1NSxcbiAgICAgICAgMTM2LFxuICAgICAgICA4LFxuICAgICAgICAxOCxcbiAgICAgICAgMTUxLFxuICAgICAgICA2MCxcbiAgICAgICAgMjAxLFxuICAgICAgICAyMzgsXG4gICAgICAgIDMsXG4gICAgICAgIDEwNixcbiAgICAgICAgNyxcbiAgICAgICAgMixcbiAgICAgICAgMTMwLFxuICAgICAgICA1MSxcbiAgICAgICAgMTM4LFxuICAgICAgICAxNixcbiAgICAgICAgMTcyLFxuICAgICAgICAxNzUsXG4gICAgICAgIDI0MixcbiAgICAgICAgNDAsXG4gICAgICAgIDI1NCxcbiAgICAgICAgNyxcbiAgICAgICAgOTYsXG4gICAgICAgIDgwLFxuICAgICAgICA0MSxcbiAgICAgICAgMjAyLFxuICAgICAgICA0MSxcbiAgICAgICAgODcsXG4gICAgICAgIDI0NSxcbiAgICAgICAgNThcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkSWRlbnRpdHlLZXlcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDEzNixcbiAgICAgICAgMjE0LFxuICAgICAgICA3LFxuICAgICAgICAyOSxcbiAgICAgICAgMzAsXG4gICAgICAgIDE1OCxcbiAgICAgICAgMTEzLFxuICAgICAgICA0NSxcbiAgICAgICAgODQsXG4gICAgICAgIDE5LFxuICAgICAgICA2NSxcbiAgICAgICAgNzksXG4gICAgICAgIDY0LFxuICAgICAgICAxMDMsXG4gICAgICAgIDEzLFxuICAgICAgICA0OSxcbiAgICAgICAgMjAsXG4gICAgICAgIDI1NCxcbiAgICAgICAgMTUzLFxuICAgICAgICAxOTEsXG4gICAgICAgIDE2MixcbiAgICAgICAgMzMsXG4gICAgICAgIDk0LFxuICAgICAgICAxMjgsXG4gICAgICAgIDIyNyxcbiAgICAgICAgMjQ3LFxuICAgICAgICAxNjAsXG4gICAgICAgIDE4LFxuICAgICAgICA3NyxcbiAgICAgICAgMjA3LFxuICAgICAgICAxNDIsXG4gICAgICAgIDEwNFxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyMzMsXG4gICAgICAgIDc0LFxuICAgICAgICA3NSxcbiAgICAgICAgMTIyLFxuICAgICAgICAyMDgsXG4gICAgICAgIDc2LFxuICAgICAgICAyMDIsXG4gICAgICAgIDMzLFxuICAgICAgICAyMTMsXG4gICAgICAgIDE1NyxcbiAgICAgICAgMjQ1LFxuICAgICAgICAyNTUsXG4gICAgICAgIDM0LFxuICAgICAgICAyMjksXG4gICAgICAgIDEzMixcbiAgICAgICAgMTIsXG4gICAgICAgIDIsXG4gICAgICAgIDE2OSxcbiAgICAgICAgMjQzLFxuICAgICAgICAyMDgsXG4gICAgICAgIDI2LFxuICAgICAgICAxMTUsXG4gICAgICAgIDExNCxcbiAgICAgICAgMTkyLFxuICAgICAgICAxNjUsXG4gICAgICAgIDUyLFxuICAgICAgICAxNzQsXG4gICAgICAgIDI0MSxcbiAgICAgICAgMTg0LFxuICAgICAgICAyMTksXG4gICAgICAgIDE4MCxcbiAgICAgICAgNTVcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkUHJlS2V5XCI6IHtcbiAgICBcImtleVBhaXJcIjoge1xuICAgICAgXCJwcml2YXRlXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgNDgsXG4gICAgICAgICAgMTM0LFxuICAgICAgICAgIDE1NixcbiAgICAgICAgICAxODMsXG4gICAgICAgICAgMzUsXG4gICAgICAgICAgMTQyLFxuICAgICAgICAgIDU5LFxuICAgICAgICAgIDE5NCxcbiAgICAgICAgICAxMDcsXG4gICAgICAgICAgMTA3LFxuICAgICAgICAgIDExMixcbiAgICAgICAgICA0MCxcbiAgICAgICAgICAyMzIsXG4gICAgICAgICAgMjM2LFxuICAgICAgICAgIDUzLFxuICAgICAgICAgIDEwMSxcbiAgICAgICAgICAyMDYsXG4gICAgICAgICAgOTAsXG4gICAgICAgICAgMjIwLFxuICAgICAgICAgIDI0OSxcbiAgICAgICAgICAzNCxcbiAgICAgICAgICAyNDQsXG4gICAgICAgICAgMTAwLFxuICAgICAgICAgIDE3NixcbiAgICAgICAgICAxMTYsXG4gICAgICAgICAgMjgsXG4gICAgICAgICAgMjExLFxuICAgICAgICAgIDE3NSxcbiAgICAgICAgICAxNDMsXG4gICAgICAgICAgMTYxLFxuICAgICAgICAgIDIxMixcbiAgICAgICAgICA4M1xuICAgICAgICBdXG4gICAgICB9LFxuICAgICAgXCJwdWJsaWNcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA4MyxcbiAgICAgICAgICAxNDcsXG4gICAgICAgICAgOTcsXG4gICAgICAgICAgMTc4LFxuICAgICAgICAgIDEwLFxuICAgICAgICAgIDIxLFxuICAgICAgICAgIDE4MyxcbiAgICAgICAgICAyNCxcbiAgICAgICAgICA4MyxcbiAgICAgICAgICAxMTUsXG4gICAgICAgICAgMjIwLFxuICAgICAgICAgIDIwNyxcbiAgICAgICAgICAyNTUsXG4gICAgICAgICAgMTY1LFxuICAgICAgICAgIDE3MixcbiAgICAgICAgICAzOCxcbiAgICAgICAgICAzNCxcbiAgICAgICAgICAyMDAsXG4gICAgICAgICAgMTQ3LFxuICAgICAgICAgIDEyMSxcbiAgICAgICAgICAyMTQsXG4gICAgICAgICAgMTA2LFxuICAgICAgICAgIDE0OSxcbiAgICAgICAgICAyNTQsXG4gICAgICAgICAgMTA3LFxuICAgICAgICAgIDEzNCxcbiAgICAgICAgICA3NSxcbiAgICAgICAgICAxMjMsXG4gICAgICAgICAgOTQsXG4gICAgICAgICAgMTQ0LFxuICAgICAgICAgIDIyOSxcbiAgICAgICAgICA1MFxuICAgICAgICBdXG4gICAgICB9XG4gICAgfSxcbiAgICBcInNpZ25hdHVyZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE0LFxuICAgICAgICA4NCxcbiAgICAgICAgMTU3LFxuICAgICAgICAzOCxcbiAgICAgICAgMjE1LFxuICAgICAgICA5NyxcbiAgICAgICAgMjUxLFxuICAgICAgICAyMDksXG4gICAgICAgIDc3LFxuICAgICAgICAxMDMsXG4gICAgICAgIDkxLFxuICAgICAgICAxNzAsXG4gICAgICAgIDE1MCxcbiAgICAgICAgMTYxLFxuICAgICAgICAxOTQsXG4gICAgICAgIDE0NyxcbiAgICAgICAgMzcsXG4gICAgICAgIDE2MyxcbiAgICAgICAgOTksXG4gICAgICAgIDQ1LFxuICAgICAgICA1NCxcbiAgICAgICAgMTk0LFxuICAgICAgICAxNTYsXG4gICAgICAgIDEyNixcbiAgICAgICAgNDgsXG4gICAgICAgIDE5NixcbiAgICAgICAgMTgzLFxuICAgICAgICAyNSxcbiAgICAgICAgMTU1LFxuICAgICAgICA0MCxcbiAgICAgICAgNTEsXG4gICAgICAgIDI0MSxcbiAgICAgICAgMTE2LFxuICAgICAgICAxODgsXG4gICAgICAgIDQ3LFxuICAgICAgICAyMTQsXG4gICAgICAgIDgxLFxuICAgICAgICAyMzQsXG4gICAgICAgIDQ2LFxuICAgICAgICAxMTcsXG4gICAgICAgIDUwLFxuICAgICAgICAxMjksXG4gICAgICAgIDI0MyxcbiAgICAgICAgMixcbiAgICAgICAgMjEzLFxuICAgICAgICA2LFxuICAgICAgICAxMzMsXG4gICAgICAgIDE2NixcbiAgICAgICAgMTQyLFxuICAgICAgICA0OSxcbiAgICAgICAgMjI3LFxuICAgICAgICAxNDcsXG4gICAgICAgIDQxLFxuICAgICAgICA5OSxcbiAgICAgICAgMTc4LFxuICAgICAgICAyMjEsXG4gICAgICAgIDEyMSxcbiAgICAgICAgMjE3LFxuICAgICAgICA5OCxcbiAgICAgICAgMTAsXG4gICAgICAgIDE5OSxcbiAgICAgICAgNzQsXG4gICAgICAgIDE2MSxcbiAgICAgICAgMTM0XG4gICAgICBdXG4gICAgfSxcbiAgICBcImtleUlkXCI6IDFcbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25JZFwiOiAyMzQsXG4gIFwiYWR2U2VjcmV0S2V5XCI6IFwiU2VTb3JwUVpTbkZwQXYxTVZuSjhPclViOU9vRkxPSTNDVVNVTGFOTkFzMD1cIixcbiAgXCJwcm9jZXNzZWRIaXN0b3J5TWVzc2FnZXNcIjogW1xuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCI5MjMwOTc0ODEwMTJAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIjk4OEVCNUFCOTg2MDZGMkM4OUFFNTQ2NUJFRTlENjVDXCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTcyOTU2NzAzNlxuICAgIH1cbiAgXSxcbiAgXCJuZXh0UHJlS2V5SWRcIjogMzEsXG4gIFwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWRcIjogMzEsXG4gIFwiYWNjb3VudFN5bmNDb3VudGVyXCI6IDEsXG4gIFwiYWNjb3VudFNldHRpbmdzXCI6IHtcbiAgICBcInVuYXJjaGl2ZUNoYXRzXCI6IGZhbHNlXG4gIH0sXG4gIFwiZGV2aWNlSWRcIjogXCJiaUpWOW82QVJRNm5RazBkZUZVQktnXCIsXG4gIFwicGhvbmVJZFwiOiBcIjJkZmNkYmJjLTQ3MTItNGIzOC04ZDNlLWYzNTA5MzU0ZDcxNVwiLFxuICBcImlkZW50aXR5SWRcIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICAxMzQsXG4gICAgICA5NyxcbiAgICAgIDEzNSxcbiAgICAgIDE1NCxcbiAgICAgIDQ1LFxuICAgICAgNDcsXG4gICAgICAyMDQsXG4gICAgICA4NixcbiAgICAgIDIwMyxcbiAgICAgIDk5LFxuICAgICAgMjE0LFxuICAgICAgMTMwLFxuICAgICAgMjEzLFxuICAgICAgOTgsXG4gICAgICA1NyxcbiAgICAgIDE5NCxcbiAgICAgIDIzMixcbiAgICAgIDIwMCxcbiAgICAgIDQ2LFxuICAgICAgMTk4XG4gICAgXVxuICB9LFxuICBcInJlZ2lzdGVyZWRcIjogdHJ1ZSxcbiAgXCJiYWNrdXBUb2tlblwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDMzLFxuICAgICAgMjE0LFxuICAgICAgMjU1LFxuICAgICAgMjQyLFxuICAgICAgMTA4LFxuICAgICAgMTUzLFxuICAgICAgMTY0LFxuICAgICAgMTE4LFxuICAgICAgMTQwLFxuICAgICAgMTAwLFxuICAgICAgMzMsXG4gICAgICA1OCxcbiAgICAgIDIxLFxuICAgICAgMjI4LFxuICAgICAgMjQ1LFxuICAgICAgMjUwLFxuICAgICAgMTcxLFxuICAgICAgNzIsXG4gICAgICA5NCxcbiAgICAgIDExXG4gICAgXVxuICB9LFxuICBcInJlZ2lzdHJhdGlvblwiOiB7fSxcbiAgXCJwYWlyaW5nQ29kZVwiOiBcIjM4VEQ1RzVLXCIsXG4gIFwibWVcIjoge1xuICAgIFwiaWRcIjogXCI5MjMwOTc0ODEwMTI6NEBzLndoYXRzYXBwLm5ldFwiLFxuICAgIFwibGlkXCI6IFwiMjQ3MjI3NDYxMTY5NDA2OjRAbGlkXCJcbiAgfSxcbiAgXCJhY2NvdW50XCI6IHtcbiAgICBcImRldGFpbHNcIjogXCJDSmZaMmVRRkVMR3kzTGdHR0FFZ0FDZ0FcIixcbiAgICBcImFjY291bnRTaWduYXR1cmVLZXlcIjogXCJWbG91V0ZWaVZCVXplNXpySmJHLzlUdVBkbWUwUzh1cm1yZXg1dE41bWpVPVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZVwiOiBcIk4wMllidjIyY3lxNXJncU0reVRIR1JiVit3TjFxYzNGemFRWWNaWUJXRnZkWWplVGhTeDZESUZRNEs4OTBJczJ0Qlc0Uk44Y3ZmY1RoZ2N6WWdZbEJBPT1cIixcbiAgICBcImRldmljZVNpZ25hdHVyZVwiOiBcIkFvQ3lKb0ZVUHZLNFlBcWRrZDZFWFdmb21mbGNQNGJiRTlZdjNTMlhzT0dpRGJMT202YlpOOUNJRTdYYUtzUGFzYnBBZXNrdm9Wcm1neTV0UTdGN2hRPT1cIlxuICB9LFxuICBcInNpZ25hbElkZW50aXRpZXNcIjogW1xuICAgIHtcbiAgICAgIFwiaWRlbnRpZmllclwiOiB7XG4gICAgICAgIFwibmFtZVwiOiBcIjkyMzA5NzQ4MTAxMjo0QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZGV2aWNlSWRcIjogMFxuICAgICAgfSxcbiAgICAgIFwiaWRlbnRpZmllcktleVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDUsXG4gICAgICAgICAgODYsXG4gICAgICAgICAgOTAsXG4gICAgICAgICAgNDYsXG4gICAgICAgICAgODgsXG4gICAgICAgICAgODUsXG4gICAgICAgICAgOTgsXG4gICAgICAgICAgODQsXG4gICAgICAgICAgMjEsXG4gICAgICAgICAgNTEsXG4gICAgICAgICAgMTIzLFxuICAgICAgICAgIDE1NixcbiAgICAgICAgICAyMzUsXG4gICAgICAgICAgMzcsXG4gICAgICAgICAgMTc3LFxuICAgICAgICAgIDE5MSxcbiAgICAgICAgICAyNDUsXG4gICAgICAgICAgNTksXG4gICAgICAgICAgMTQzLFxuICAgICAgICAgIDExOCxcbiAgICAgICAgICAxMDMsXG4gICAgICAgICAgMTgwLFxuICAgICAgICAgIDc1LFxuICAgICAgICAgIDIwMyxcbiAgICAgICAgICAxNzEsXG4gICAgICAgICAgMTU0LFxuICAgICAgICAgIDE4MyxcbiAgICAgICAgICAxNzcsXG4gICAgICAgICAgMjMwLFxuICAgICAgICAgIDIxMSxcbiAgICAgICAgICAxMjEsXG4gICAgICAgICAgMTU0LFxuICAgICAgICAgIDUzXG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9XG4gIF0sXG4gIFwicGxhdGZvcm1cIjogXCJhbmRyb2lkXCIsXG4gIFwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wXCI6IDE3Mjk1NjcwMjksXG4gIFwibXlBcHBTdGF0ZUtleUlkXCI6IFwiQUFBQUFBZlFcIlxufSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUFmUS5qc29uIjogIntcImtleURhdGFcIjpcIjh2UzFRUG1CdlhPQzlYd1BGakpjZ0ptQjd6czROYnB1OVZHdjZ2cWg1ZlU9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTU1MzM2MjA3MSxcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIxNzI5NTY3MDMzMTU3XCJ9Igp9",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
